"""Update 05.01.2026

Revision ID: 384e401e7a17
Revises: 7e00f5210e2c
Create Date: 2026-01-05 11:03:19.822582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384e401e7a17'
down_revision: Union[str, Sequence[str], None] = '7e00f5210e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('dataset_preprocess_json', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('optimizer_json', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('scheduler_json', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('loss_function', sa.Enum('CROSS_ENTROPY', 'MSE', 'L1', 'SMOOTH_L1', name='losstype'), nullable=True))
    op.create_foreign_key(None, 'projects', 'datasets', ['dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'loss_function')
    op.drop_column('projects', 'scheduler_json')
    op.drop_column('projects', 'optimizer_json')
    op.drop_column('projects', 'dataset_preprocess_json')
    op.drop_column('projects', 'dataset_id')
    # ### end Alembic commands ###
