"""Project table was modified (connected to DB table)

Revision ID: b2e0367a86a7
Revises: 609181af87eb
Create Date: 2025-12-21 10:50:11.250003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e0367a86a7'
down_revision: Union[str, Sequence[str], None] = '609181af87eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'datasets', ['dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'dataset_id')
    # ### end Alembic commands ###
