"""JSON line for project added

Revision ID: c72c9fe16400
Revises: faf09516e446
Create Date: 2025-10-17 16:21:41.555339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72c9fe16400'
down_revision: Union[str, Sequence[str], None] = 'faf09516e446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('architecture_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'architecture_json')
    # ### end Alembic commands ###
