"""Upd

Revision ID: c7b82b667dfd
Revises: b2e0367a86a7
Create Date: 2025-12-23 09:38:03.305265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b82b667dfd'
down_revision: Union[str, Sequence[str], None] = 'b2e0367a86a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('dataset_preprocess_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'dataset_preprocess_json')
    # ### end Alembic commands ###
