"""projects table modified

Revision ID: c924e6d4798c
Revises: 4b33a7eb7f92
Create Date: 2025-09-07 07:03:28.228960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c924e6d4798c'
down_revision: Union[str, Sequence[str], None] = '4b33a7eb7f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('input_type', sa.Enum('NOISE', 'IMAGE', 'NUMBERS', name='datatype'), nullable=False))
    op.add_column('projects', sa.Column('output_type', sa.Enum('NOISE', 'IMAGE', 'NUMBERS', name='datatype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'output_type')
    op.drop_column('projects', 'input_type')
    # ### end Alembic commands ###
