"""Optimizer, criterion and scheduler data added to projects table

Revision ID: 7e00f5210e2c
Revises: c7b82b667dfd
Create Date: 2025-12-31 13:51:21.761653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e00f5210e2c'
down_revision: Union[str, Sequence[str], None] = 'c7b82b667dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('optimizer_json', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('scheduler_json', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('loss_function', sa.Enum('CROSS_ENTROPY', 'MSE', 'L1', 'SMOOTH_L1', name='losstype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'loss_function')
    op.drop_column('projects', 'scheduler_json')
    op.drop_column('projects', 'optimizer_json')
    # ### end Alembic commands ###
