name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} # Заменили key на password
          script: |
            # Замени /root/my-project на точный путь к твоему годовому проекту
            cd /root/Maturitni-projekt 
            # cd /root 
            
            git pull origin main
            
            # Используем docker compose (через пробел), так как в Ubuntu 24.04 это стандарт
            docker compose up -d --build --remove-orphans